runtime: python312  # or whatever Python version you are using

entrypoint: gunicorn django_serve_react.wsgi:application --bind 0.0.0.0:8080

env_variables:
  DJANGO_SETTINGS_MODULE: 'django_serve_react.settings'
  DEBUG: 'False'
  APPENGINE_URL: https://django-gae-pfw.uc.r.appspot.com

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5

handlers:
  # Whitenoise is used to serve static files
  # # Serve static files Google Cloud Storage
  # - url: /staticfiles
  #   static_dir: staticfiles/
  #   secure: always
  #   redirect_http_response_code: 301

  # All URLs are handled by the app itself
  - url: /.*
    script: auto
    secure: always