version: '3'

services:
  web:
    build: .
    volumes:
      - .:/app
    expose:
      - 8000
    depends_on:
      - nginx

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./staticfiles:/app/staticfiles
