name: Cypress Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.2'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Node.js for Cypress
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install Cypress dependencies
      run: |
        cd front_end
        npm install
        ls

    - name: Start Django app
      run: |
        python manage.py migrate
        python manage.py collectstatic --noinput
        gunicorn django_serve_react.wsgi:application --bind 0.0.0.0:8000 &
      env:
        DJANGO_SETTINGS_MODULE: django_serve_react.settings

    - name: Run Cypress Tests
      uses: cypress-io/github-action@v2
      with:
        start: npm run test_cypress
        working-directory: ./front_end
        wait-on: 'http://localhost:8000'
        headless: true
        config-file: cypress.config.js
        
